# Experiment name
experiment: "SAN_chrome2013"

# Random seed
seed: 20200814

# Training parameters
epoches: 200
batch_size: 8
gradient_accumulation_steps: 1
workers: 0
optimizer: Adadelta
lr: 0.3
lr_decay: cosine
step_ratio: 10
eps: 1e-6
weight_decay: 1e-4
beta: 0.9
image_resize: True
# max dimensions
image_width: 1600
image_height: 320
image_channel: 1
dropout: True
dropout_ratio: 0.5
relu: True
gradient: 100
gradient_clip: True
use_label_mask: False

# Training data
train_image_path: '../data/chrome2013/train_image.pkl'
train_label_path: '../data/chrome2013/train_label.pkl'
eval_image_path: '../data/chrome2013/test_image.pkl'
eval_label_path: '../data/chrome2013/test_label.pkl'

word_path: '../data/chrome2013/word.txt'

# Encoder selection
encoder:
  net: DenseNet
  input_channels: 1
  out_channels: 684

resnet:
  conv1_stride: 1

densenet:
  ratio: 16
  growthRate: 24
  reduction: 0.5
  bottleneck: True
  use_dropout: True

# RNN cell to use
decoder:
  net: SAN_decoder
  cell: 'GRU'
  input_size: 256
  hidden_size: 256
  inverse: False

# Attention parameters
attention:
  attention_dim: 512
  use_position_encoding: True
  # Learnable weights to balance attention terms (initialized values)
  query_weight: 2.0
  coverage_weight: 4.0
  features_weight: 0.5
  position_encoding_weight: 1.0  

# hybrid tree
hybrid_tree:
  threshold: 0.5

# Training weights save path
optimizer_save: False
checkpoint_dir: 'checkpoints'
finetune: True
checkpoint: "checkpoints/best.pth"

# TensorBoard path
log_dir: 'logs'