/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MathDrawer {
        "clearCanvas": () => Promise<void>;
        "convertToLatex": () => Promise<void>;
    }
}
declare global {
    interface HTMLMathDrawerElement extends Components.MathDrawer, HTMLStencilElement {
    }
    var HTMLMathDrawerElement: {
        prototype: HTMLMathDrawerElement;
        new (): HTMLMathDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "math-drawer": HTMLMathDrawerElement;
    }
}
declare namespace LocalJSX {
    interface MathDrawer {
    }
    interface IntrinsicElements {
        "math-drawer": MathDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "math-drawer": LocalJSX.MathDrawer & JSXBase.HTMLAttributes<HTMLMathDrawerElement>;
        }
    }
}
