/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { HandwritingCanvasState } from "./components/akit-handwriting-canvas/types";
export { HandwritingCanvasState } from "./components/akit-handwriting-canvas/types";
export namespace Components {
    interface AkitHandwritingCanvas {
        "clearCanvas": () => Promise<void>;
        "convertToLatex": () => Promise<void>;
        "getState": () => Promise<HandwritingCanvasState>;
        "redo": () => Promise<void>;
        "restoreState": (state: HandwritingCanvasState) => Promise<void>;
        /**
          * @default false
         */
        "showSubmitButton": boolean;
        "undo": () => Promise<void>;
    }
}
export interface AkitHandwritingCanvasCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAkitHandwritingCanvasElement;
}
declare global {
    interface HTMLAkitHandwritingCanvasElementEventMap {
        "latexChanged": { latex: string };
        "submitted": { latex: string };
    }
    interface HTMLAkitHandwritingCanvasElement extends Components.AkitHandwritingCanvas, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAkitHandwritingCanvasElementEventMap>(type: K, listener: (this: HTMLAkitHandwritingCanvasElement, ev: AkitHandwritingCanvasCustomEvent<HTMLAkitHandwritingCanvasElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAkitHandwritingCanvasElementEventMap>(type: K, listener: (this: HTMLAkitHandwritingCanvasElement, ev: AkitHandwritingCanvasCustomEvent<HTMLAkitHandwritingCanvasElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAkitHandwritingCanvasElement: {
        prototype: HTMLAkitHandwritingCanvasElement;
        new (): HTMLAkitHandwritingCanvasElement;
    };
    interface HTMLElementTagNameMap {
        "akit-handwriting-canvas": HTMLAkitHandwritingCanvasElement;
    }
}
declare namespace LocalJSX {
    interface AkitHandwritingCanvas {
        "onLatexChanged"?: (event: AkitHandwritingCanvasCustomEvent<{ latex: string }>) => void;
        "onSubmitted"?: (event: AkitHandwritingCanvasCustomEvent<{ latex: string }>) => void;
        /**
          * @default false
         */
        "showSubmitButton"?: boolean;
    }
    interface IntrinsicElements {
        "akit-handwriting-canvas": AkitHandwritingCanvas;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "akit-handwriting-canvas": LocalJSX.AkitHandwritingCanvas & JSXBase.HTMLAttributes<HTMLAkitHandwritingCanvasElement>;
        }
    }
}
