/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SymbolAdjustment } from "./components/akit-config-handwriting/types";
import { HandwritingCanvasState, SymbolAdjustment as SymbolAdjustment1 } from "./components/akit-handwriting-canvas/types";
export { SymbolAdjustment } from "./components/akit-config-handwriting/types";
export { HandwritingCanvasState, SymbolAdjustment as SymbolAdjustment1 } from "./components/akit-handwriting-canvas/types";
export namespace Components {
    interface AkitConfigHandwriting {
        /**
          * @default []
         */
        "adjustments": SymbolAdjustment[];
    }
    interface AkitHandwritingCanvas {
        /**
          * Clears the canvas without emitting latexChanged event. Use erase() to clear and emit.
         */
        "clearCanvas": () => Promise<void>;
        "getState": () => Promise<HandwritingCanvasState>;
        "redo": () => Promise<void>;
        "restoreState": (state: HandwritingCanvasState) => Promise<void>;
        /**
          * @default false
         */
        "showSubmitButton": boolean;
        /**
          * @default []
         */
        "symbolAdjustments": SymbolAdjustment1[];
        "undo": () => Promise<void>;
    }
}
export interface AkitConfigHandwritingCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAkitConfigHandwritingElement;
}
export interface AkitHandwritingCanvasCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAkitHandwritingCanvasElement;
}
declare global {
    interface HTMLAkitConfigHandwritingElementEventMap {
        "adjustmentsChanged": { adjustments: SymbolAdjustment[] };
    }
    interface HTMLAkitConfigHandwritingElement extends Components.AkitConfigHandwriting, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAkitConfigHandwritingElementEventMap>(type: K, listener: (this: HTMLAkitConfigHandwritingElement, ev: AkitConfigHandwritingCustomEvent<HTMLAkitConfigHandwritingElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAkitConfigHandwritingElementEventMap>(type: K, listener: (this: HTMLAkitConfigHandwritingElement, ev: AkitConfigHandwritingCustomEvent<HTMLAkitConfigHandwritingElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAkitConfigHandwritingElement: {
        prototype: HTMLAkitConfigHandwritingElement;
        new (): HTMLAkitConfigHandwritingElement;
    };
    interface HTMLAkitHandwritingCanvasElementEventMap {
        "latexChanged": { latex: string };
        "submitted": { latex: string };
    }
    interface HTMLAkitHandwritingCanvasElement extends Components.AkitHandwritingCanvas, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAkitHandwritingCanvasElementEventMap>(type: K, listener: (this: HTMLAkitHandwritingCanvasElement, ev: AkitHandwritingCanvasCustomEvent<HTMLAkitHandwritingCanvasElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAkitHandwritingCanvasElementEventMap>(type: K, listener: (this: HTMLAkitHandwritingCanvasElement, ev: AkitHandwritingCanvasCustomEvent<HTMLAkitHandwritingCanvasElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAkitHandwritingCanvasElement: {
        prototype: HTMLAkitHandwritingCanvasElement;
        new (): HTMLAkitHandwritingCanvasElement;
    };
    interface HTMLElementTagNameMap {
        "akit-config-handwriting": HTMLAkitConfigHandwritingElement;
        "akit-handwriting-canvas": HTMLAkitHandwritingCanvasElement;
    }
}
declare namespace LocalJSX {
    interface AkitConfigHandwriting {
        /**
          * @default []
         */
        "adjustments"?: SymbolAdjustment[];
        "onAdjustmentsChanged"?: (event: AkitConfigHandwritingCustomEvent<{ adjustments: SymbolAdjustment[] }>) => void;
    }
    interface AkitHandwritingCanvas {
        "onLatexChanged"?: (event: AkitHandwritingCanvasCustomEvent<{ latex: string }>) => void;
        "onSubmitted"?: (event: AkitHandwritingCanvasCustomEvent<{ latex: string }>) => void;
        /**
          * @default false
         */
        "showSubmitButton"?: boolean;
        /**
          * @default []
         */
        "symbolAdjustments"?: SymbolAdjustment1[];
    }
    interface IntrinsicElements {
        "akit-config-handwriting": AkitConfigHandwriting;
        "akit-handwriting-canvas": AkitHandwritingCanvas;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "akit-config-handwriting": LocalJSX.AkitConfigHandwriting & JSXBase.HTMLAttributes<HTMLAkitConfigHandwritingElement>;
            "akit-handwriting-canvas": LocalJSX.AkitHandwritingCanvas & JSXBase.HTMLAttributes<HTMLAkitHandwritingCanvasElement>;
        }
    }
}
